= xtend-ioc
:icons: font

== Introduction

_xtend-ioc_ is a compile-time inversion of control framework for http://www.eclipse.org/xtend/[Xtend]. +
Its main features are

* component instantiation and lifecycle management,
* dependency injection, and
* event dispatching between component instances and
* aspect-oriented programming using method interceptors.

For more information see

* the link:latest/index.html[latest documentation] or
* the https://github.com/NorbertSandor/xtend-ioc[GitHub page].

== History

=== 0.6.0-SNAPSHOT

Current development version.

=== 0.5.3 (2016-05-04)

* Fix: problems with Maven Central deploy

Documentation: link:0.5.3/index.html[0.5.3]

=== 0.5.2 (2016-05-04)

* Fix: problems with Maven Central deploy

Documentation: link:0.5.2/index.html[0.5.2]

=== 0.5.1 (2016-05-04)

* Fix: project generated from archetype uses incorrect xtend-ioc version.

Documentation: link:0.5.1/index.html[0.5.1]

=== 0.5.0 (2016-05-03)

* Upgrade xtend-contrib to 1.0.0
* Upgrade xtend to 2.9.2
* Added archetype
* Better GWT support
* Support @Any
* Support @Default
* Support events with qualifiers

Documentation: link:0.5.0/index.html[0.5.0]

=== 0.4.0 (2015-12-19)

* Code cleanup, improvements and bug fixes in the framework code
* Build system improvements
* Documentation improvements, new example (logger injection with parameterized component provider)
* Upgrade xtend to 2.9.1

Documentation: link:0.4.0/index.html[0.4.0]

=== 0.3.0 (2015-12-09)

* Upgrade to xtend-2.9.0
* Upgrade to Java 8
* Code cleanup, improvements and bug fixes in the framework code

Documentation: link:0.3.0/index.html[0.3.0]

=== 0.2.1 (2015-11-15)

* Build system improvements

Documentation: link:0.2.1/index.html[0.2.1]

=== 0.2.0 (2015-11-15)

* First implementation of interceptors
* Upgrade xtend to 2.9.0.rc1
* Many bug fixes

Documentation: link:0.2.0/index.html[0.2.0]

=== 0.1.0 (2015-11-09)

Initial release +
(Development was started on 2015-09-02.)

Documentation: link:0.1.0/index.html[0.1.0]

++++
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-69896656-1', 'auto');
  ga('send', 'pageview');

</script>
++++
