= xtend-ioc
:icons: font

== Introduction

_xtend-ioc_ is a compile-time inversion of control framework for http://www.eclipse.org/xtend/[Xtend]. +
Its main features are

* component instantiation and lifecycle management,
* dependency injection, and
* event dispatching between component instances and
* aspect-oriented programming using method interceptors.

For more details see

* the link:latest/index.html[latest documentation] or
* the https://github.com/NorbertSandor/xtend-ioc[GitHub page].

== History

=== 0.2.1 (2015-11-15)

* Build system improvements.

=== 0.2.0 (2015-11-15)

* First implementation of interceptors.
* Upgrade xtend to 2.9.0.rc1.
* Many bug fixes.

Documentation: link:0.2.0/index.html[0.2.0]

=== 0.1.0 (2015-11-09)

Initial release. +
(Development was started on 2015-09-02.)

Documentation: link:0.1.0/index.html[0.1.0]

++++
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-69896656-1', 'auto');
  ga('send', 'pageview');

</script>
++++
